# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4119ebea8abb0ff479190291bc6cbf90d1d4da6e114e6bfbddb7cedc567e6d6141a7c3eabbad525fb5936b65eab4608a58d8c8b11b1f468f9daca5fa44f31579

test:
  secret_key_base: 64a9d3cd9fe6ede2516981286680fdb432cd252ef9e37ea5eaa8e9dfca1ea97a5e2516360691c55a3a42358e833547284331b040134fac5d2b2a293feac15550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
